# Generated by Django 3.2 on 2022-11-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(max_length=252, null=True),
        ),
    ]
