# Generated by Django 4.1.2 on 2022-11-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_msgfile_remove_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msgfile',
            name='image',
        ),
    ]
