# Generated by Django 4.1.2 on 2022-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_msgfile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='MsgFile',
        ),
    ]
