# Generated by Django 4.1.2 on 2022-11-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_filemodel_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='doc',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
