# Generated by Django 4.1.2 on 2022-11-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_image_alter_filemodel_doc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
